version: "3"
services:
    whatsapp-chatgpt:
        build: .
        container_name: whatsapp-chatgpt
        env_file:
            - .env
        volumes:
            - session-data:/app/session
volumes:
    session-data:
